inputs_def:
  - handle: files
    description: Input
    json_schema:
      type: array
      items:
        type: string
  - handle: prefix
    json_schema:
      type: string
    nullable: true
  - handle: suffix
    json_schema:
      type: string
    nullable: true
outputs_def:
  - handle: files
    description: Output
    json_schema:
      type: array
      items:
        type: string
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Prefix Name Suffix
icon: ":fa6-solid:pen-to-square:"
