inputs_def:
  - handle: dir
    description: Input
    json_schema:
      type: string
      ui:widget: dir
  - handle: model
    json_schema:
      enum:
        - oomol-VL
      ui:options:
        labels:
          - oomol-VL
    value: oomol-VL
    nullable: true
outputs_def:
  - handle: dir
    description: Output
    json_schema:
      type: string
      ui:widget: dir
  - handle: images
    json_schema:
      type: array
      items:
        type: string
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: AI Rename
icon: ":carbon:edit:"
