inputs_def:
  - handle: input_file
    description: Input
    json_schema:
      type: string
      ui:widget: dir
outputs_def:
  - handle: output
    description: Output
    json_schema:
      type: string
      ui:widget: dir
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: AI Rename
icon: ":fa6-solid:square-pen:"
